### ISSUE TITLE
[I] "Patch on update" patch: FAIL

### ISSUE THREAD

**Issue by shinkuan** [exys228/osu-stuff#22]
As the title says, the osu!patch.CLI Failed when trying to do "Patch on update" patch.
```
C:\Users\user>osu-stuff-master\osu-stuff-master\osu!patch.CLI\bin\Release\osu!patch.CLI.exe osu-stuff-master\osu-stuff-master\osu!patch\bin\Release\osu!patch\clean.exe C:\Users\user\AppData\Local\osu!\osu!.exe
[I] Loaded assemblies: osu!, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null (clean); osu!, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null (obfuscated).
[I] MD5 hash of obfuscated assembly: 8877e262e337b4128679b67f67a856d6
[I] Now loading all custom add-ons from plugins/ folder.
[I] Cleaning control flow of obfuscated assembly
[I] Fixing strings in obfuscated assembly.
[I] Found cached name dictionary file for this assembly! Loading names...
[I] Done! Now patching.
[I] "Unsigned executable" fix: DONE
[I] Bancho MD5 hash of osu!.exe fix: DONE
[I] "Patch on update" patch: FAIL
[I] Done processing all local patches! Now processing patches from loaded add-ons...
[I] Done processing all plugins.
[I] There's some details about failed patches.
Patch name: "Patch on update" patch
Execution result: Exception
Exception details:
osu_patch.Exceptions.NameProviderException: Unable to find method specified!
   at osu_patch.Explorers.TypeExplorer.FindMethod(String name, MethodSig sig)
   at osu_patch.LocalPatches.<>c.<.cctor>b__1_2(Patch patch, ModuleExplorer exp)
   at osu_patch.Patch.Execute(ModuleExplorer exp)

[I] There are some failed patches. Do you want to continue?
[W] In case of self-update pressing 'N' will leave stock version of osu! without patching it!
    Continue? (y/n)
[E] [I] Aborted by user.
```
![Fail擷取](https://user-images.githubusercontent.com/35415788/92246312-2a778f00-eef8-11ea-903c-53330edd38ac.PNG)

**Comment by xxCherry** [comment]
send cache folder

**Comment by shinkuan** [comment]
[cache.zip](https://github.com/exys228/osu-stuff/files/5175930/cache.zip)

**Comment by shinkuan** [comment]
If you need it, here is my file:
[All.zip](https://github.com/exys228/osu-stuff/files/5177391/All.zip)
Contains:
 Clean ver
 Original ver
 StringFixer ver
 NameMapped ver

**Comment by Hazuki-san** [comment]
this is my clean.exe, have you try it?

**Comment by Hazuki-san** [comment]
[clean.zip](https://github.com/exys228/osu-stuff/files/5183756/clean.zip)

**Comment by shinkuan** [comment]
Same result, Failed to "Patch on update".

```
[I] Loaded assemblies: osu!, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null (clean); osu!, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null (obfuscated).
[I] MD5 hash of obfuscated assembly: 8877e262e337b4128679b67f67a856d6
[I] Now loading all custom add-ons from plugins/ folder.
[I] Cleaning control flow of obfuscated assembly
[I] Fixing strings in obfuscated assembly.
[I] Found cached name dictionary file for this assembly! Loading names...
[I] Done! Now patching.
[I] "Unsigned executable" fix: DONE
[I] Bancho MD5 hash of osu!.exe fix: DONE
[I] "Patch on update" patch: FAIL
[I] Done processing all local patches! Now processing patches from loaded add-ons...
[I] Done processing all plugins.
[I] There's some details about failed patches.
Patch name: "Patch on update" patch
Execution result: Exception
Exception details:
osu_patch.Exceptions.NameProviderException: Unable to find method specified!
   於 osu_patch.Explorers.TypeExplorer.FindMethod(String name, MethodSig sig)
   於 osu_patch.LocalPatches.<>c.<.cctor>b__1_2(Patch patch, ModuleExplorer exp)
   於 osu_patch.Patch.Execute(ModuleExplorer exp)

[I] There are some failed patches. Do you want to continue?
[W] In case of self-update pressing 'N' will leave stock version of osu! without patching it!
    Continue? (y/n)
[E] [I] Aborted by user.
```

**Comment by Hazuki-san** [comment]
Try disable them in "patcher.cfg"

**Comment by Hazuki-san** [comment]
It's because osu! base code got updated, we'll have to make a new OpCodes method

**Comment by shinkuan** [comment]
I disabled it, and it worked.
Does it mean I have to patch manually when osu! updates?

**Comment by Hazuki-san** [comment]
Yes, sadly.

**Comment by Hazuki-san** [comment]
You can use my forked version of this repository, if you want to disable updates.
